#!/bin/bash -
opt=$1
shift
if [ "x$opt" = "x-e" ]; then
    cmd="mysql --default-character-set=utf8 -h10.38.161.32 -umf_admin -pmf123 -e '$1'"
    eval $cmd
else
    mysql -v --default-character-set=utf8 -h10.38.161.32 -umf_admin -pmf123
fi
