#!/bin/bash -

info=$(java -version 2>&1 | head -1)

if echo $info | grep '1.7' > /dev/null; then 
    rm /home/m/Share/jdk/current 
    ln -s /home/m/Share/jdk/java/jdk1.8.0_131 /home/m/Share/jdk/current
    echo "switch to java 1.8"
else
    rm /home/m/Share/jdk/current 
    ln -s /home/m/Share/jdk/java/jdk1.7.0_65 /home/m/Share/jdk/current
    echo "switch to java 1.7"
fi
