#!/usr/bin/python
import sys

key = ''
value = ''

def main(argv):
    global key, value
    for line in sys.stdin.readlines():
        ps = line.strip().split(' ')
        if ps[0] == key:
            key = ps[0]
            value = '%s %s'%(value,' '.join(ps[1:])
        else:
            if len(key) > 0:
                print '%s %s'%(key,value)
            key = ps[0]
            value = ' '.join(ps[1:])
    print '%s %s'%(key,value)

if __name__ == '__main__':
    import sys
    sys.exit(main(sys.argv))
