#!/bin/bash -x
target_war="$@"
cp_path="/home/mi/LocEnv/tomcat/apache-tomcat-9.0.0.M22/webapps"
TOMCAT_HOME="/home/mi/LocEnv/tomcat/apache-tomcat-9.0.0.M22"

if [ -f "$target_war" ]; then
    if [ -f "$cp_path/foo.war" ]; then
        rm -r $cp_path/foo 
        rm -r $cp_path/foo.war
    fi
    cp $target_war $cp_path/foo.war 
fi

pushd $TOMCAT_HOME/bin
   ./shutdown.sh
   ./startup.sh 
popd
