#!/bin/bash -
cmd="uptime"
echo "$cmd" && eval "$cmd"
echo "------------------------------------"
cmd="dmesg"
echo "$cmd" && eval "$cmd"
echo "------------------------------------"
cmd="vmstat 1 10"
echo "$cmd" && eval "$cmd"
echo "------------------------------------"
cmd="pidstat 1 10"
echo "$cmd" && eval "$cmd"
echo "------------------------------------"
cmd="iostat 1 10"
echo "$cmd" && eval "$cmd"
echo "------------------------------------"
cmd="free -m"
echo "$cmd" && eval "$cmd"
echo "------------------------------------"
cmd="sar -n DEV 1 10"
echo "$cmd" && eval "$cmd"
echo "------------------------------------"
