#!/usr/bin/env python
import os
import sys
import argparse

def eprint(*args, **kwargs):
    print(args, sys.stderr, kwargs)

def do_sum(args):
    sum_num = 0
    with open('/dev/stdin') as f:
        for line in iter(f):
            record = line.strip()
            if len(record) > 0:
                try:
                    params = record.split(args.d)
                    try:
                        s = int(params[args.f].strip())
                        sum_num = sum_num + s
                    except Exception as msg:
                        eprint(msg)
                        return
                except Exception as message:
                    eprint(message)
                    return
    print(sum_num)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='sum tool')
    parser.add_argument('-f', default=0, help='field num to sum')
    parser.add_argument('-d', default=' ', help='seperator')
    args = parser.parse_args()
    do_sum(args)
