#!/usr/bin/env python
import os
import sys
import argparse

def realpath():
    if len(sys.argv) == 1:
        return os.system('pwd')
    if len(sys.argv) >= 2:
        fpath = sys.argv[1]
        if os.path.isdir(fpath):
            return os.path.realpath(fpath)+'/'
        if os.path.isfile(fpath):
            return os.path.realpath(fpath)
    return "Invalid argvs"

if __name__ == '__main__':
    print(realpath())
