#!/bin/bash -
cat <<EOF

a) 创建分支 git branch 分支名

b) 切换分支 git checkout 分支名

c) 合并分支 git merge 分支名 （将其他分支合并到当千分支）

d) 查看当前分支 git branch

e) 查看所有分支 git br -a

f) 添加代码 git add -A

g) 提交版本 git commit -m ‘版本注释’

h) 拉取远程代码 git pull

i) 将代码推到远端 git pull

j) 删除本地分支 git branch -d 分支名

k) 删除远程分支 git push origin --delete 分支名

l) 创建远程分支 git push origin 分支名

m) 从远程分支拉取到本地 git checkout origin/远程分支 -b 本地分支

EOF
